name: PR checks
on: [pull_request]
jobs:
  run_tests:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-18.04]
        platform: [iOS, macOS, SPM]
        include:
          - platform: iOS
            destination: OS=latest,name=iPhone 8
            scheme: WebP iOS
            workspace: WebP.xcworkspace
            sdk: iphonesimulator
          - platform: macOS
            destination: platform=OS X,arch=x86_64
            scheme: WebP macOS
            workspace: WebP.xcworkspace
            sdk: macosx
        exclude:
          - os: ubuntu-18.04
            platform: iOS
          - os: ubuntu-18.04
            platform: macOS
    name: Run Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests with xcodebuild against ${{ matrix.platform }} platform
        if: matrix.platform != 'SPM'
        run: ./.github/bin/test.sh
        env:
          DESTINATION: ${{ matrix.destination }}
          SCHEME: ${{ matrix.scheme }}
          WORKSPACE: ${{ matrix.workspace }}
          SDK: ${{ matrix.sdk }}
      - name: Run Tests with Swift Package Manager
        if: matrix.platform == 'SPM' && matrix.os == 'macOS-latest'
        run: |
          set -o pipefail
          brew install pkg-config webp
          xcversion select 11.0
          swift test -v
      - name: Run Tests with Swift Package Manager
        if: matrix.platform == 'SPM' && matrix.os == 'ubuntu-18.04'
        uses: docker://swift:5.1
        with:
          entrypoint: .github/bin/entrypoint.sh
          github_token: ${{ secrets.github_token }}
          github_actor: ainame
